# Generated by Django 3.1.2 on 2020-10-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.book'),
        ),
    ]
