# Generated by Django 3.1.2 on 2020-10-04 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201004_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.book'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='reader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.reader'),
        ),
    ]
