# Generated by Django 3.1.2 on 2020-10-04 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20201004_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn10',
            field=models.CharField(default='xxxxxxxxxx', max_length=11, verbose_name='ISBN10'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn13',
            field=models.CharField(default='xxxxxxxxxxxxx', max_length=14, verbose_name='ISBN13'),
        ),
        migrations.AddField(
            model_name='book',
            name='lang',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=2, verbose_name='Lang'),
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.CharField(max_length=500, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(max_length=500, null=True, verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='book',
            name='x',
            field=models.FloatField(default=0.0, verbose_name='X'),
        ),
        migrations.AddField(
            model_name='book',
            name='y',
            field=models.FloatField(default=0.0, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
